services:
  - type: web
    name: smart-traffic-vision
    env: docker
    region: frankfurt # or ohio, oregon etc.
    plan: free # using the free tier
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
